package com.example.jetpackcomposebasics

enum class ComposeFeatureType(val resourceId: Int) {
    None(R.string.None),
    Alert(R.string.Alert),
    AlertDialog(R.string.AlertDialog),
    Animations(R.string.Animations),                     // androidx.compose.animation.*
    BackdropScaffold(R.string.BackdropScaffold),
    Badge(R.string.Badge),
    BadgedBox(R.string.BadgedBox),
    BottomAppBar(R.string.BottomAppBar),
    BottomDrawer(R.string.BottomDrawer),
    BottomNavigation(R.string.BottomNavigation),
    BottomSheetScaffold(R.string.BottomSheetScaffold),
    Button(R.string.Button),
    ButtonAnimation(R.string.ButtonAnimation),
    Card(R.string.Card),
    Checkbox(R.string.Checkbox),
    Chip(R.string.Chip),
    CustomView(R.string.CustomView),
    Divider(R.string.Divider),
    DropdownMenu(R.string.DropdownMenu),
    DropdownMenuItem(R.string.DropdownMenuItem),
    EditTextField(R.string.EditTextField),
    ExposedDropdownMenuBox(R.string.ExposedDropdownMenuBox),
    ExtendedFloatingActionButton(R.string.ExtendedFloatingActionButton),
    FilterChip(R.string.FilterChip),
    FloatingActionButton(R.string.FloatingActionButton),
    Gestures(R.string.Gestures),                       // androidx.compose.foundation.gestures
    Icon(R.string.Icon),
    Interactions(R.string.Interactions),                   // androidx.compose.foundation.interaction
    LeadingIconTab(R.string.LeadingIconTab),
    List(R.string.List),
    ListItem(R.string.ListItem),
    ModalBottomSheetLayout(R.string.ModalBottomSheetLayout),
    ModalDrawer(R.string.ModalDrawer),
    NavigationRail(R.string.NavigationRail),
    NavigationRailItem(R.string.NavigationRailItem),
    OutlinedTextField(R.string.OutlinedTextField),
    ProgressIndicator(R.string.ProgressIndicator),
    ProvideTextStyle(R.string.ProvideTextStyle),
    RadioButton(R.string.RadioButton),
    RangeSlider(R.string.RangeSlider),
    ScrollableTabRow(R.string.ScrollableTabRow),
    Slider(R.string.Slider),
    Snackbar(R.string.Snackbar),
    SnackbarHost(R.string.SnackbarHost),
    Surface(R.string.Surface),
    SwipeToDismiss(R.string.SwipeToDismiss),
    Switch(R.string.Switch),
    Tab(R.string.Tab),
    TabRow(R.string.TabRow),
    Text(R.string.Text),
    TextField(R.string.TextField),
    TopAppBar(R.string.TopAppBar),
    TriStateCheckbox(R.string.TriStateCheckbox),
    UiGraphics(R.string.UiGraphics),                          // androidx.compose.ui.graphics
    UiUtil(R.string.UiUtil)                              // androidx.compose.ui.util
}
